In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import requests
import pandas as pd
from datetime import datetime

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_records = []
start_year = 2021   # last 5 years
end_year = 2025

for year in range(start_year, end_year + 1):
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        response = requests.get(url, params=params)
        if response.status_code != 200:
            print(f"⚠️ Failed for {start_date}: {response.text[:200]}")
            continue

        try:
            data = response.json()
        except Exception as e:
            print(f"⚠️ JSON error for {start_date}: {e}")
            continue

        for f in data["features"]:
            p = f["properties"]
            g = f["geometry"]["coordinates"]
            all_records.append({
                "id": f.get("id"),
                "time": pd.to_datetime(p.get("time"), unit="ms"),
                "updated": pd.to_datetime(p.get("updated"), unit="ms"),
                "latitude": g[1] if g else None,
                "longitude": g[0] if g else None,
                "depth_km": g[2] if g else None,
                "mag": p.get("mag"),
                "magType" : p.get("magType"),
                "place": p.get("place"),
                "status" : p.get("status"),
                "tsunami": p.get("tsunami"),
                "alert": p.get("alert"),
                "felt": p.get("felt"),
                "cdi": p.get("cdi"),
                "mmi": p.get("mmi"),
                "sig": p.get("sig"),
                "net": p.get("net"),
                "code": p.get("code"),
                "ids": p.get("ids"),
                "sources": p.get("sources"),
                "types": p.get("types"),
                "nst": p.get("nst"),
                "dmin": p.get("dmin"),
                "rms": p.get("rms"),
                "gap": p.get("gap"),
                "type": p.get("type")


                })

df = pd.DataFrame(all_records)

In [4]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,net,code,ids,sources,types,nst,dmin,rms,gap,type
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.270,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,us,6000ddi8,",us6000ddi8,",",us,",",dyfi,moment-tensor,origin,phase-data,",NaN,0.294,0.82,42.0,earthquake
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.710,4.1,mb,Fiji region,reviewed,...,us,6000dev6,",us6000dev6,",",us,",",origin,phase-data,",NaN,1.471,0.29,64.0,earthquake
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.730,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,us,6000dev5,",us6000dev5,",",us,",",origin,phase-data,",NaN,3.057,0.69,106.0,earthquake
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.000,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,us,6000ddhs,",us6000ddhs,",",us,",",origin,phase-data,",NaN,3.330,0.61,71.0,earthquake
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.000,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,us,6000dev4,",us6000dev4,",",us,",",origin,phase-data,",NaN,6.023,0.50,65.0,earthquake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104436,ak2025xpgfse,2025-12-01 01:51:06.974,2026-02-25 16:18:40.040,59.1380,-150.6400,15.200,3.2,ml,"60 km SSE of Halibut Cove, Alaska",reviewed,...,ak,2025xpgfse,",us7000ret4,ak2025xpgfse,",",us,ak,",",origin,phase-data,",100.0,0.600,0.90,149.0,earthquake
104437,us7000ret3,2025-12-01 01:41:43.796,2026-02-25 16:18:40.040,7.4127,127.0704,35.000,4.6,mb,"53 km E of Baculin, Philippines",reviewed,...,us,7000ret3,",us7000ret3,",",us,",",origin,phase-data,",74.0,1.518,1.19,96.0,earthquake
104438,us7000ret2,2025-12-01 01:37:57.834,2026-02-25 16:18:40.040,-19.4176,-67.2761,227.844,4.1,mb,"78 km SW of Challapata, Bolivia",reviewed,...,us,7000ret2,",us7000ret2,",",us,",",origin,phase-data,",14.0,2.371,0.73,95.0,earthquake
104439,us7000resz,2025-12-01 01:25:46.725,2026-02-25 16:18:40.040,47.3283,-113.2019,30.159,3.1,ml,"27 km NE of Seeley Lake, Montana",reviewed,...,us,7000resz,",us7000resz,",",us,",",origin,phase-data,",48.0,0.293,0.53,45.0,earthquake
104440,us7000resx,2025-12-01 00:48:01.683,2026-02-25 16:18:40.040,42.0602,142.5913,57.662,4.6,mb,"19 km WSW of Urakawa, Japan",reviewed,...,us,7000resx,",us7000resx,",",us,",",origin,phase-data,",51.0,0.424,0.52,83.0,earthquake

In [5]:
df.info() # to get data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104441 entries, 0 to 104440
Data columns (total 26 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         104441 non-null  object
 1   time       104441 non-null  datetime64[ns]
 2   updated    104441 non-null  datetime64[ns]
 3   latitude   104441 non-null  float64
 4   longitude  104441 non-null  float64
 5   depth_km   104441 non-null  float64
 6   mag        104441 non-null  float64
 7   magType    104441 non-null  object
 8   place      104441 non-null  object
 9   status     104441 non-null  object
 10  tsunami    104441 non-null  int64
 11  alert      4255 non-null    object
 12  felt       16206 non-null   float64
 13  cdi        16206 non-null   float64
 14  mmi        8539 non-null    float64
 15  sig        104441 non-null  int64
 16  net        104441 non-null  object
 17  code       104441 non-null  object
 18  ids        104441 non-null  object
 19  sources    104441 non-null  object
 20  types      104441 non-null  object
 21  nst        76680 non-null   float64
 22  dmin       100468 non-null  float64
 23  rms        104423 non-null  float64
 24  gap        101420 non-null  float64
 25  type       104441 non-null  object
dtypes: datetime64[ns](2), float64(11), int64(2), object(11)
memory usage: 20.7+ MB

In [6]:
df.shape # rows and columns counts

(104441, 26)

In [7]:
df.head() # first 5 rows

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,net,code,ids,sources,types,nst,dmin,rms,gap,type
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,us,6000ddi8,",us6000ddi8,",",us,",",dyfi,moment-tensor,origin,phase-data,",NaN,0.294,0.82,42.0,earthquake
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,us,6000dev6,",us6000dev6,",",us,",",origin,phase-data,",NaN,1.471,0.29,64.0,earthquake
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,us,6000dev5,",us6000dev5,",",us,",",origin,phase-data,",NaN,3.057,0.69,106.0,earthquake
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,us,6000ddhs,",us6000ddhs,",",us,",",origin,phase-data,",NaN,3.330,0.61,71.0,earthquake
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,us,6000dev4,",us6000dev4,",",us,",",origin,phase-data,",NaN,6.023,0.50,65.0,earthquake

In [8]:
df["place"]

0               29 km SW of Villa Basilio Nievas, Argentina
1                                               Fiji region
2                           103 km SW of Basco, Philippines
3                                   114 km N of M?n?b, Iran
4         184 km ENE of Olonkinbyen, Svalbard and Jan Mayen
                                ...
104436                    60 km SSE of Halibut Cove, Alaska
104437                      53 km E of Baculin, Philippines
104438                      78 km SW of Challapata, Bolivia
104439                     27 km NE of Seeley Lake, Montana
104440                          19 km WSW of Urakawa, Japan
Name: place, Length: 104441, dtype: object

In [9]:
df["place"]=df["place"].str.extract(r"(?:,\s*)?([^,]+)$")[0]

In [10]:
df["place"].value_counts()

place
Alaska                             12396
Indonesia                           7839
Russia                              5688
Japan                               4512
Philippines                         4351
                                   ...
Panama-Colombia border region          1
Lake Almanor Earthquake                1
Trinidad                               1
Taiwan Earthquake                      1
2025 Hubbard Glacier Earthquake        1
Name: count, Length: 527, dtype: int64

In [11]:
df["alert"].isnull().sum() #this col has null.

np.int64(100186)

In [12]:
df["alert"].value_counts()

alert
green     4085
yellow     124
red         24
orange      22
Name: count, dtype: int64

In [13]:
df["alert"]=df["alert"].fillna(df["alert"].mode()[0])#nan values fillna.mode()

In [14]:
df["alert"].value_counts()

alert
green     104271
yellow       124
red           24
orange        22
Name: count, dtype: int64

In [15]:
df["magType"]

0         mwr
1          mb
2          mb
3          mb
4          mb
         ...
104436     ml
104437     mb
104438     mb
104439     ml
104440     mb
Name: magType, Length: 104441, dtype: object

In [16]:
df["magType"].value_counts() #there is no null .

magType
mb            74318
ml            14857
mww            6356
md             5620
mwr            2485
mw              595
mb_lg           115
ml(texnet)       43
mwb              29
mlr              10
mlv               5
mwc               2
ms_vx             2
ms_20             1
mlg               1
mwp               1
mh                1
Name: count, dtype: int64

In [17]:
df["magType"]=df["magType"].str.lower() #changing all string are lowercase.

In [19]:
df["status"].value_counts() #there is no null and 2unique row (reviewed,automatic)

status
reviewed     104292
automatic       149
Name: count, dtype: int64

In [20]:
df["status"]=df["status"].str.lower() #changing all string are lowercase.

In [21]:
df["type"]=df["type"].str.lower() #changing all string are lowercase.

In [22]:
df["type"] # there is no null ,but type and magtype are same

0         earthquake
1         earthquake
2         earthquake
3         earthquake
4         earthquake
             ...
104436    earthquake
104437    earthquake
104438    earthquake
104439    earthquake
104440    earthquake
Name: type, Length: 104441, dtype: object

In [23]:
df["net"]=df["net"].str.lower() #changing all string are lowercase.
df["sources"]=df["sources"].str.lower() #changing all string are lowercase.
df["types"]=df["types"].str.lower() #changing all string are lowercase.

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104441 entries, 0 to 104440
Data columns (total 26 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         104441 non-null  object
 1   time       104441 non-null  datetime64[ns]
 2   updated    104441 non-null  datetime64[ns]
 3   latitude   104441 non-null  float64
 4   longitude  104441 non-null  float64
 5   depth_km   104441 non-null  float64
 6   mag        104441 non-null  float64
 7   magType    104441 non-null  object
 8   place      104441 non-null  object
 9   status     104441 non-null  object
 10  tsunami    104441 non-null  int64
 11  alert      104441 non-null  object
 12  felt       16206 non-null   float64
 13  cdi        16206 non-null   float64
 14  mmi        8539 non-null    float64
 15  sig        104441 non-null  int64
 16  net        104441 non-null  object
 17  code       104441 non-null  object
 18  ids        104441 non-null  object
 19  sources    104441 non-null  object
 20  types      104441 non-null  object
 21  nst        76680 non-null   float64
 22  dmin       100468 non-null  float64
 23  rms        104423 non-null  float64
 24  gap        101420 non-null  float64
 25  type       104441 non-null  object
dtypes: datetime64[ns](2), float64(11), int64(2), object(11)
memory usage: 20.7+ MB

In [25]:
df["sources"].value_counts() #there is no null

sources
,us,                       76589
,ak,us,                     8877
,us,ak,                     2665
,pr,                        2494
,us,pr,                     2387
                           ...
,ak,ak,us,ak,                  1
,us,ew,nn,usauto,pt,nn,        1
,us,ak,at,usauto,ak,           1
,ak,ak,usauto,us,              1
,ew,us,nc,at,usauto,pt,        1
Name: count, Length: 352, dtype: int64

In [26]:
df["sources"]=df["sources"].str.strip(',') # removing the , in the string

In [27]:
df["sources"]

0            us
1            us
2            us
3            us
4            us
          ...
104436    us,ak
104437       us
104438       us
104439       us
104440       us
Name: sources, Length: 104441, dtype: object

In [28]:
df["types"] #there is no null

0         ,dyfi,moment-tensor,origin,phase-data,
1                            ,origin,phase-data,
2                            ,origin,phase-data,
3                            ,origin,phase-data,
4                            ,origin,phase-data,
                           ...
104436                       ,origin,phase-data,
104437                       ,origin,phase-data,
104438                       ,origin,phase-data,
104439                       ,origin,phase-data,
104440                       ,origin,phase-data,
Name: types, Length: 104441, dtype: object

In [31]:
df["types"]=df["types"].str.strip(',')# removing the , in the string

In [32]:
df["types"].value_counts()

types
origin,phase-data                                                                                                         79557
dyfi,origin,phase-data                                                                                                     8209
earthquake-name,origin,phase-data                                                                                          2172
origin,phase-data,shakemap                                                                                                 1639
dyfi,moment-tensor,origin,phase-data                                                                                       1268
                                                                                                                          ...
associate,general-header,impact-text,origin,phase-data,shakemap                                                               1
associate,dyfi,internal-moment-tensor,moment-tensor,origin,phase-data                                                         1
dyfi,general-text,moment-tensor,origin,phase-data,significance                                                                1
dyfi,event-sequence,losspager,moment-tensor,oaf,origin,phase-data,shakemap,trump-shakemap                                     1
dyfi,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap        1
Name: count, Length: 553, dtype: int64

In [33]:
df["ids"]=df["ids"].str.strip(',')# removing the , in the string

In [34]:
df["ids"]

0                      us6000ddi8
1                      us6000dev6
2                      us6000dev5
3                      us6000ddhs
4                      us6000dev4
                   ...
104436    us7000ret4,ak2025xpgfse
104437                 us7000ret3
104438                 us7000ret2
104439                 us7000resz
104440                 us7000resx
Name: ids, Length: 104441, dtype: object

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104441 entries, 0 to 104440
Data columns (total 26 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         104441 non-null  object
 1   time       104441 non-null  datetime64[ns]
 2   updated    104441 non-null  datetime64[ns]
 3   latitude   104441 non-null  float64
 4   longitude  104441 non-null  float64
 5   depth_km   104441 non-null  float64
 6   mag        104441 non-null  float64
 7   magType    104441 non-null  object
 8   place      104441 non-null  object
 9   status     104441 non-null  object
 10  tsunami    104441 non-null  int64
 11  alert      104441 non-null  object
 12  felt       16206 non-null   float64
 13  cdi        16206 non-null   float64
 14  mmi        8539 non-null    float64
 15  sig        104441 non-null  int64
 16  net        104441 non-null  object
 17  code       104441 non-null  object
 18  ids        104441 non-null  object
 19  sources    104441 non-null  object
 20  types      104441 non-null  object
 21  nst        76680 non-null   float64
 22  dmin       100468 non-null  float64
 23  rms        104423 non-null  float64
 24  gap        101420 non-null  float64
 25  type       104441 non-null  object
dtypes: datetime64[ns](2), float64(11), int64(2), object(11)
memory usage: 20.7+ MB

In [36]:
df["mag"]

0         4.7
1         4.1
2         4.7
3         4.9
4         4.0
         ...
104436    3.2
104437    4.6
104438    4.1
104439    3.1
104440    4.6
Name: mag, Length: 104441, dtype: float64

In [37]:
df["mag"].unique()

array([4.7       , 4.1       , 4.9       , 4.        , 3.55      ,
       3.27      , 3.48      , 4.3       , 4.2       , 3.24      ,
       3.21      , 5.5       , 3.        , 3.57      , 3.44      ,
       3.41      , 3.46      , 3.04      , 4.6       , 4.5       ,
       3.03      , 4.4       , 3.1       , 5.3       , 4.8       ,
       3.22      , 3.3       , 3.36      , 5.        , 3.2       ,
       3.39      , 3.4       , 3.58      , 5.2       , 3.56      ,
       3.43      , 3.07      , 3.18      , 3.38      , 5.7       ,
       5.4       , 3.9       , 3.8       , 3.14      , 3.25      ,
       3.32      , 3.37      , 3.7       , 3.5       , 3.05      ,
       3.06      , 3.6       , 3.42      , 3.59      , 3.54      ,
       3.45      , 3.17      , 3.31      , 3.49      , 3.61      ,
       3.29      , 5.1       , 3.01      , 3.34      , 3.23      ,
       5.8       , 6.9       , 3.16      , 3.11      , 3.68      ,
       3.85      , 5.6       , 3.71      , 3.78      , 3.51      ,
       3.65      , 3.52      , 3.76      , 3.69      , 3.62      ,
       3.92      , 7.        , 3.19      , 3.99      , 3.53      ,
       3.15      , 3.09      , 3.77      , 3.33      , 3.28      ,
       3.66      , 6.4       , 4.39      , 3.75      , 4.02      ,
       3.08      , 3.73      , 3.96      , 3.63      , 6.2       ,
       3.84      , 5.9       , 3.12      , 4.34      , 3.13      ,
       6.7       , 6.1       , 3.93      , 5.05      , 3.98      ,
       3.86      , 3.79      , 3.02      , 6.3       , 3.47      ,
       3.91      , 3.35      , 3.95      , 4.32      , 3.94      ,
       3.87      , 5.14      , 5.16      , 3.81      , 3.89      ,
       3.67      , 5.06      , 7.1       , 4.03      , 6.        ,
       4.04      , 7.7       , 3.82      , 3.26      , 3.74      ,
       4.99      , 4.38      , 4.18      , 3.83      , 4.05      ,
       4.75      , 4.69      , 4.09      , 6.6       , 4.07      ,
       5.18      , 4.23      , 4.12      , 5.17      , 6.5       ,
       8.1       , 7.4       , 7.3       , 3.72      , 3.64      ,
       4.27      , 4.36      , 4.15      , 5.24      , 5.07      ,
       4.65      , 3.97      , 4.06      , 4.46      , 4.43      ,
       4.24      , 4.01      , 4.1407    , 4.19      , 4.08      ,
       4.41      , 4.29      , 5.25      , 3.88      , 8.2       ,
       4.35      , 5.12      , 4.26      , 5.08      , 4.55      ,
       4.63      , 4.31      , 5.03      , 4.17      , 4.37      ,
       7.2       , 7.5       , 4.11      , 4.13      , 4.25      ,
       4.28      , 4.47      , 4.45      , 6.21      , 5.21      ,
       5.09      , 4.87      , 4.84      , 5.65      , 4.44      ,
       4.22      , 4.67      , 6.8       , 4.58      , 4.54      ,
       4.33      , 4.53      , 4.16      , 4.14      , 4.62      ,
       3.80347518, 3.03      , 7.6       , 3.08210262, 4.0930297 ,
       4.66      , 3.36783186, 5.02      , 3.07999992, 4.92      ,
       4.42      , 5.35      , 4.78      , 7.8       , 5.58      ,
       5.48      , 4.57      , 3.01      , 3.05      , 4.83      ,
       4.31      , 3.26      , 4.56      , 4.81      , 4.61      ,
       5.88      , 3.07      , 4.86      , 4.48      , 4.74      ,
       5.22      , 4.71246919, 4.72      , 4.68      , 3.51      ,
       5.85      , 3.71944208, 4.52      , 3.98016705, 5.63      ,
       4.3723843 , 8.8       , 4.51      , 3.87489612, 3.63545491,
       3.49613297, 3.86904151, 3.20045406, 3.52750637, 3.38862784,
       3.13980998, 3.05506959, 3.08399283, 3.03661569, 3.33110536,
       3.80438226, 3.03769108, 3.10812757, 3.58360704, 3.08527785,
       3.04115447, 3.05176565, 3.11374937, 3.13933191, 3.55738127,
       3.85562555, 3.64512857, 3.20911468, 3.75136768, 5.08766699])

In [38]:
df["depth_km"].unique()

array([ 17.27 , 426.71 ,  46.73 , ..., 227.844,  30.159,  57.662])

In [40]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,net,code,ids,sources,types,nst,dmin,rms,gap,type
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.270,4.7,mwr,Argentina,reviewed,...,us,6000ddi8,us6000ddi8,us,"dyfi,moment-tensor,origin,phase-data",NaN,0.294,0.82,42.0,earthquake
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.710,4.1,mb,Fiji region,reviewed,...,us,6000dev6,us6000dev6,us,"origin,phase-data",NaN,1.471,0.29,64.0,earthquake
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.730,4.7,mb,Philippines,reviewed,...,us,6000dev5,us6000dev5,us,"origin,phase-data",NaN,3.057,0.69,106.0,earthquake
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.000,4.9,mb,Iran,reviewed,...,us,6000ddhs,us6000ddhs,us,"origin,phase-data",NaN,3.330,0.61,71.0,earthquake
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.000,4.0,mb,Svalbard and Jan Mayen,reviewed,...,us,6000dev4,us6000dev4,us,"origin,phase-data",NaN,6.023,0.50,65.0,earthquake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104436,ak2025xpgfse,2025-12-01 01:51:06.974,2026-02-25 16:18:40.040,59.1380,-150.6400,15.200,3.2,ml,Alaska,reviewed,...,ak,2025xpgfse,"us7000ret4,ak2025xpgfse","us,ak","origin,phase-data",100.0,0.600,0.90,149.0,earthquake
104437,us7000ret3,2025-12-01 01:41:43.796,2026-02-25 16:18:40.040,7.4127,127.0704,35.000,4.6,mb,Philippines,reviewed,...,us,7000ret3,us7000ret3,us,"origin,phase-data",74.0,1.518,1.19,96.0,earthquake
104438,us7000ret2,2025-12-01 01:37:57.834,2026-02-25 16:18:40.040,-19.4176,-67.2761,227.844,4.1,mb,Bolivia,reviewed,...,us,7000ret2,us7000ret2,us,"origin,phase-data",14.0,2.371,0.73,95.0,earthquake
104439,us7000resz,2025-12-01 01:25:46.725,2026-02-25 16:18:40.040,47.3283,-113.2019,30.159,3.1,ml,Montana,reviewed,...,us,7000resz,us7000resz,us,"origin,phase-data",48.0,0.293,0.53,45.0,earthquake
104440,us7000resx,2025-12-01 00:48:01.683,2026-02-25 16:18:40.040,42.0602,142.5913,57.662,4.6,mb,Japan,reviewed,...,us,7000resx,us7000resx,us,"origin,phase-data",51.0,0.424,0.52,83.0,earthquake

In [41]:
df["nst"]

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
          ...
104436    100.0
104437     74.0
104438     14.0
104439     48.0
104440     51.0
Name: nst, Length: 104441, dtype: float64

In [42]:
df["nst"]=df["nst"].fillna(df["nst"].median())

In [43]:
df["nst"]

0          32.0
1          32.0
2          32.0
3          32.0
4          32.0
          ...
104436    100.0
104437     74.0
104438     14.0
104439     48.0
104440     51.0
Name: nst, Length: 104441, dtype: float64

In [44]:
df["dmin"]

0         0.294
1         1.471
2         3.057
3         3.330
4         6.023
          ...
104436    0.600
104437    1.518
104438    2.371
104439    0.293
104440    0.424
Name: dmin, Length: 104441, dtype: float64

In [45]:
df["dmin"]=df["dmin"].fillna(df["dmin"].median())

In [46]:
df["dmin"]

0         0.294
1         1.471
2         3.057
3         3.330
4         6.023
          ...
104436    0.600
104437    1.518
104438    2.371
104439    0.293
104440    0.424
Name: dmin, Length: 104441, dtype: float64

In [47]:
df["rms"]

0         0.82
1         0.29
2         0.69
3         0.61
4         0.50
          ...
104436    0.90
104437    1.19
104438    0.73
104439    0.53
104440    0.52
Name: rms, Length: 104441, dtype: float64

In [48]:
df["rms"]=df["rms"].fillna(df["rms"].mean())

In [49]:
df["rms"].value_counts()

rms
0.6700    1745
0.6200    1741
0.6400    1736
0.6800    1729
0.7000    1724
          ...
0.1129       1
0.1899       1
0.1554       1
0.1641       1
0.2189       1
Name: count, Length: 503, dtype: int64

In [50]:
df["gap"]=df["gap"].fillna(df["gap"].median())

In [51]:
df["gap"]

0          42.0
1          64.0
2         106.0
3          71.0
4          65.0
          ...
104436    149.0
104437     96.0
104438     95.0
104439     45.0
104440     83.0
Name: gap, Length: 104441, dtype: float64

In [52]:
df["sig"]

0         344
1         259
2         340
3         369
4         246
         ...
104436    158
104437    326
104438    259
104439    148
104440    326
Name: sig, Length: 104441, dtype: int64

In [53]:
df["alert"]=df["alert"].str.lower()

In [54]:
df["felt"]

0         12.0
1          NaN
2          NaN
3          NaN
4          NaN
          ...
104436     NaN
104437     NaN
104438     NaN
104439     NaN
104440     NaN
Name: felt, Length: 104441, dtype: float64

In [55]:
df["felt"]=df["felt"].fillna(df["felt"].median())

In [56]:
df["felt"]

0         12.0
1          3.0
2          3.0
3          3.0
4          3.0
          ...
104436     3.0
104437     3.0
104438     3.0
104439     3.0
104440     3.0
Name: felt, Length: 104441, dtype: float64

In [57]:
df["cdi"]

0         3.7
1         NaN
2         NaN
3         NaN
4         NaN
         ...
104436    NaN
104437    NaN
104438    NaN
104439    NaN
104440    NaN
Name: cdi, Length: 104441, dtype: float64

In [58]:
df["cdi"]=df["cdi"].fillna(df["cdi"].median())

In [59]:
df["cdi"]

0         3.7
1         3.1
2         3.1
3         3.1
4         3.1
         ...
104436    3.1
104437    3.1
104438    3.1
104439    3.1
104440    3.1
Name: cdi, Length: 104441, dtype: float64

In [60]:
df["mmi"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
104436   NaN
104437   NaN
104438   NaN
104439   NaN
104440   NaN
Name: mmi, Length: 104441, dtype: float64

In [61]:
df["mmi"]=df["mmi"].fillna(df["mmi"].median())

In [62]:
df["mmi"]

0         3.442
1         3.442
2         3.442
3         3.442
4         3.442
          ...
104436    3.442
104437    3.442
104438    3.442
104439    3.442
104440    3.442
Name: mmi, Length: 104441, dtype: float64

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104441 entries, 0 to 104440
Data columns (total 26 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         104441 non-null  object
 1   time       104441 non-null  datetime64[ns]
 2   updated    104441 non-null  datetime64[ns]
 3   latitude   104441 non-null  float64
 4   longitude  104441 non-null  float64
 5   depth_km   104441 non-null  float64
 6   mag        104441 non-null  float64
 7   magType    104441 non-null  object
 8   place      104441 non-null  object
 9   status     104441 non-null  object
 10  tsunami    104441 non-null  int64
 11  alert      104441 non-null  object
 12  felt       104441 non-null  float64
 13  cdi        104441 non-null  float64
 14  mmi        104441 non-null  float64
 15  sig        104441 non-null  int64
 16  net        104441 non-null  object
 17  code       104441 non-null  object
 18  ids        104441 non-null  object
 19  sources    104441 non-null  object
 20  types      104441 non-null  object
 21  nst        104441 non-null  float64
 22  dmin       104441 non-null  float64
 23  rms        104441 non-null  float64
 24  gap        104441 non-null  float64
 25  type       104441 non-null  object
dtypes: datetime64[ns](2), float64(11), int64(2), object(11)
memory usage: 20.7+ MB

In [75]:
df["year"]=df["time"].dt.year
df["month"]=df["time"].dt.month
df["day"]=df["time"].dt.day
df["day_of_week"]=df["time"].dt.day_name()

In [76]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,types,nst,dmin,rms,gap,type,year,month,day,day_of_week
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.270,4.7,mwr,Argentina,reviewed,...,"dyfi,moment-tensor,origin,phase-data",32.0,0.294,0.82,42.0,earthquake,2021,1,31,Sunday
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.710,4.1,mb,Fiji region,reviewed,...,"origin,phase-data",32.0,1.471,0.29,64.0,earthquake,2021,1,31,Sunday
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.730,4.7,mb,Philippines,reviewed,...,"origin,phase-data",32.0,3.057,0.69,106.0,earthquake,2021,1,31,Sunday
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.000,4.9,mb,Iran,reviewed,...,"origin,phase-data",32.0,3.330,0.61,71.0,earthquake,2021,1,31,Sunday
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.000,4.0,mb,Svalbard and Jan Mayen,reviewed,...,"origin,phase-data",32.0,6.023,0.50,65.0,earthquake,2021,1,31,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104436,ak2025xpgfse,2025-12-01 01:51:06.974,2026-02-25 16:18:40.040,59.1380,-150.6400,15.200,3.2,ml,Alaska,reviewed,...,"origin,phase-data",100.0,0.600,0.90,149.0,earthquake,2025,12,1,Monday
104437,us7000ret3,2025-12-01 01:41:43.796,2026-02-25 16:18:40.040,7.4127,127.0704,35.000,4.6,mb,Philippines,reviewed,...,"origin,phase-data",74.0,1.518,1.19,96.0,earthquake,2025,12,1,Monday
104438,us7000ret2,2025-12-01 01:37:57.834,2026-02-25 16:18:40.040,-19.4176,-67.2761,227.844,4.1,mb,Bolivia,reviewed,...,"origin,phase-data",14.0,2.371,0.73,95.0,earthquake,2025,12,1,Monday
104439,us7000resz,2025-12-01 01:25:46.725,2026-02-25 16:18:40.040,47.3283,-113.2019,30.159,3.1,ml,Montana,reviewed,...,"origin,phase-data",48.0,0.293,0.53,45.0,earthquake,2025,12,1,Monday
104440,us7000resx,2025-12-01 00:48:01.683,2026-02-25 16:18:40.040,42.0602,142.5913,57.662,4.6,mb,Japan,reviewed,...,"origin,phase-data",51.0,0.424,0.52,83.0,earthquake,2025,12,1,Monday

In [79]:
def earthquake_flag(depth_km):
  if depth_km <=300:
    return "shallow"
  else:
    return "deep"

In [80]:
df["earthquake_flag"]=df["depth_km"].apply(earthquake_flag)

In [ ]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,nst,dmin,rms,gap,type,year,month,day,day_of_week,earthquake_flag
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.270,4.7,mwr,Argentina,reviewed,...,32.0,0.294,0.82,42.0,earthquake,2021,1,31,Sunday,shallow
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.710,4.1,mb,Fiji region,reviewed,...,32.0,1.471,0.29,64.0,earthquake,2021,1,31,Sunday,deep
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.730,4.7,mb,Philippines,reviewed,...,32.0,3.057,0.69,106.0,earthquake,2021,1,31,Sunday,shallow
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.000,4.9,mb,Iran,reviewed,...,32.0,3.330,0.61,71.0,earthquake,2021,1,31,Sunday,shallow
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.000,4.0,mb,Svalbard and Jan Mayen,reviewed,...,32.0,6.023,0.50,65.0,earthquake,2021,1,31,Sunday,shallow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104436,ak2025xpgfse,2025-12-01 01:51:06.974,2026-02-25 16:18:40.040,59.1380,-150.6400,15.200,3.2,ml,Alaska,reviewed,...,100.0,0.600,0.90,149.0,earthquake,2025,12,1,Monday,shallow
104437,us7000ret3,2025-12-01 01:41:43.796,2026-02-25 16:18:40.040,7.4127,127.0704,35.000,4.6,mb,Philippines,reviewed,...,74.0,1.518,1.19,96.0,earthquake,2025,12,1,Monday,shallow
104438,us7000ret2,2025-12-01 01:37:57.834,2026-02-25 16:18:40.040,-19.4176,-67.2761,227.844,4.1,mb,Bolivia,reviewed,...,14.0,2.371,0.73,95.0,earthquake,2025,12,1,Monday,shallow
104439,us7000resz,2025-12-01 01:25:46.725,2026-02-25 16:18:40.040,47.3283,-113.2019,30.159,3.1,ml,Montana,reviewed,...,48.0,0.293,0.53,45.0,earthquake,2025,12,1,Monday,shallow
104440,us7000resx,2025-12-01 00:48:01.683,2026-02-25 16:18:40.040,42.0602,142.5913,57.662,4.6,mb,Japan,reviewed,...,51.0,0.424,0.52,83.0,earthquake,2025,12,1,Monday,shallow

In [81]:
def mag_thresholds(mag):
  if mag<=5:
    return "strong"
  else:
    return "destructive"

In [82]:
df["mag_flag"]=df["mag"].apply(mag_thresholds)

In [83]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,dmin,rms,gap,type,year,month,day,day_of_week,earthquake_flag,mag_flag
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.270,4.7,mwr,Argentina,reviewed,...,0.294,0.82,42.0,earthquake,2021,1,31,Sunday,shallow,strong
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.710,4.1,mb,Fiji region,reviewed,...,1.471,0.29,64.0,earthquake,2021,1,31,Sunday,deep,strong
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.730,4.7,mb,Philippines,reviewed,...,3.057,0.69,106.0,earthquake,2021,1,31,Sunday,shallow,strong
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.000,4.9,mb,Iran,reviewed,...,3.330,0.61,71.0,earthquake,2021,1,31,Sunday,shallow,strong
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.000,4.0,mb,Svalbard and Jan Mayen,reviewed,...,6.023,0.50,65.0,earthquake,2021,1,31,Sunday,shallow,strong
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104436,ak2025xpgfse,2025-12-01 01:51:06.974,2026-02-25 16:18:40.040,59.1380,-150.6400,15.200,3.2,ml,Alaska,reviewed,...,0.600,0.90,149.0,earthquake,2025,12,1,Monday,shallow,strong
104437,us7000ret3,2025-12-01 01:41:43.796,2026-02-25 16:18:40.040,7.4127,127.0704,35.000,4.6,mb,Philippines,reviewed,...,1.518,1.19,96.0,earthquake,2025,12,1,Monday,shallow,strong
104438,us7000ret2,2025-12-01 01:37:57.834,2026-02-25 16:18:40.040,-19.4176,-67.2761,227.844,4.1,mb,Bolivia,reviewed,...,2.371,0.73,95.0,earthquake,2025,12,1,Monday,shallow,strong
104439,us7000resz,2025-12-01 01:25:46.725,2026-02-25 16:18:40.040,47.3283,-113.2019,30.159,3.1,ml,Montana,reviewed,...,0.293,0.53,45.0,earthquake,2025,12,1,Monday,shallow,strong
104440,us7000resx,2025-12-01 00:48:01.683,2026-02-25 16:18:40.040,42.0602,142.5913,57.662,4.6,mb,Japan,reviewed,...,0.424,0.52,83.0,earthquake,2025,12,1,Monday,shallow,strong

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104441 entries, 0 to 104440
Data columns (total 32 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               104441 non-null  object
 1   time             104441 non-null  datetime64[ns]
 2   updated          104441 non-null  datetime64[ns]
 3   latitude         104441 non-null  float64
 4   longitude        104441 non-null  float64
 5   depth_km         104441 non-null  float64
 6   mag              104441 non-null  float64
 7   magType          104441 non-null  object
 8   place            104441 non-null  object
 9   status           104441 non-null  object
 10  tsunami          104441 non-null  int64
 11  alert            104441 non-null  object
 12  felt             104441 non-null  float64
 13  cdi              104441 non-null  float64
 14  mmi              104441 non-null  float64
 15  sig              104441 non-null  int64
 16  net              104441 non-null  object
 17  code             104441 non-null  object
 18  ids              104441 non-null  object
 19  sources          104441 non-null  object
 20  types            104441 non-null  object
 21  nst              104441 non-null  float64
 22  dmin             104441 non-null  float64
 23  rms              104441 non-null  float64
 24  gap              104441 non-null  float64
 25  type             104441 non-null  object
 26  year             104441 non-null  int32
 27  month            104441 non-null  int32
 28  day              104441 non-null  int32
 29  day_of_week      104441 non-null  object
 30  earthquake_flag  104441 non-null  object
 31  mag_flag         104441 non-null  object
dtypes: datetime64[ns](2), float64(11), int32(3), int64(2), object(14)
memory usage: 24.3+ MB

In [86]:
df.to_csv("Cleaned_earthquake_dataset.csv", index = False)

In [88]:
import os
os.listdir()

['.config', 'Cleaned_earthquake_dataset.csv', 'sample_data']